#!/usr/bin/env sh

if [ -n "$BLOCK_INSTANCE" ]; then
  sink_name="$BLOCK_INSTANCE"
else
  sink_name=$(pactl list sinks short | head -1 | awk '{print $2}' |sed 's/.*\.//')
fi

level='5%'
no_sound='OFF'

while getopts s:l:n: opt; do
  case "$opt" in
    s) sink_name="$OPTARG" ;;
    l) level="$OPTARG" ;;
    n) no_sound="$OPTARG" ;;
  esac
done


sink=$(pactl list sinks short | grep "$sink_name" | awk '{print $1}')
mute=$(pactl list sinks | grep "Sink #$sink" -A 999999 | grep Mute | head -n1 | awk '{print $2}')

if [ "$mute" = "yes" ] ; then
  volume="$no_sound"
else
  volume="$(pactl list sinks | grep "Sink #$sink" -A 999999 | grep -P '\tVolume' | grep -P '\d+(?=%)' -o | head -1)%"
fi


case "$BLOCK_BUTTON" in
  1|4) pactl set-sink-volume "$sink" +"$level" ;;
  3|5) pactl set-sink-volume "$sink" -- -"$level" ;;
  2) pactl set-sink-mute "$sink" toggle ;;
esac


printf "%s\n" " $volume"
printf "\n"




