#!/bin/bash
#
# __  __                 __               __    ___               ___  __                               
#/\ \/\ \               /\ \             /\ \__/\_ \            /'___\/\ \__                            
#\ \ \_\ \     __   _ __\ \ \____    ____\ \ ,_\//\ \    __  __/\ \__/\ \ ,_\  __  __  __    ___ ___    
# \ \  _  \  /'__`\/\`'__\ \ '__`\  /',__\\ \ \/ \ \ \  /\ \/\ \ \ ,__\\ \ \/ /\ \/\ \/\ \ /' __` __`\  
#  \ \ \ \ \/\  __/\ \ \/ \ \ \L\ \/\__, `\\ \ \_ \_\ \_\ \ \_\ \ \ \_/ \ \ \_\ \ \_/ \_/ \/\ \/\ \/\ \ 
#   \ \_\ \_\ \____\\ \_\  \ \_,__/\/\____/ \ \__\/\____\\ \____/\ \_\   \ \__\\ \___x___/'\ \_\ \_\ \_\
#    \/_/\/_/\/____/ \/_/   \/___/  \/___/   \/__/\/____/ \/___/  \/_/    \/__/ \/__//__/   \/_/\/_/\/_/
#                                                                                                       
#                                                                                                       
# ____       _                                  __                                                      
#/\  _`\   /' \                               /'__`\                                                    
#\ \ \/\ \/\_, \    ___      __      ___ ___ /\ \/\ \                                                   
# \ \ \ \ \/_/\ \ /' _ `\  /'__`\  /' __` __`\ \ \ \ \                                                  
#  \ \ \_\ \ \ \ \/\ \/\ \/\ \L\.\_/\ \/\ \/\ \ \ \_\ \                                                 
#   \ \____/  \ \_\ \_\ \_\ \__/.\_\ \_\ \_\ \_\ \____/                                                 
#    \/___/    \/_/\/_/\/_/\/__/\/_/\/_/\/_/\/_/\/___/                                                  
#                                                                                                       
#                                                                                                       
hc() {
    herbstclient "$@"
}
 
hc emit_hook reload
 
xsetroot -solid '#5A8E3A'
 
# remove all existing keybindings
hc keyunbind --all
 
 
# close tray if reloading
killall stalonetray
 
# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier
 
feh --bg-scale ~/.config/herbstluftwm/herbstluftwm.png

# autostart
#hc spawn nitrogen --restore
hc spawn dunst
hc spawn mpd
hc spawn xfce4-power-manager
hc spawn compton -c -f -o 0.9 -D 5 -m 9 -b

#touchpad
hc spawn synclient VertEdgeScroll=1 &
hc spawn synclient HorizEdgeScroll=1 &
hc spawn synclient TapButton1=1 &

#audio
hc keybind XF86AudioRaiseVolume spawn pactl set-sink-volume 0 +5% #increase sound volume
hc keybind XF86AudioLowerVolume spawn pactl set-sink-volume 0 -5% #decrease sound volume
hc keybind XF86AudioMute spawn pactl set-sink-mute 0 toggle # mute sound

# media keys
hc keybind XF86AudioNext spawn mpc next
hc keybind XF86AudioPrev spawn mpc prev
hc keybind XF86AudioPlay spawn mpc toggle
hc keybind XF86AudioStop spawn mpc stop

hc keybind $Mod-Shift-q close
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c quit
hc keybind $Mod-Alt-l spawn lock -gpf SourceCodePro
 
# terminal
hc keybind $Mod-Return spawn termite
hc keybind $Mod-Shift-Return spawn urxvt
 
 
# start some programs
hc keybind $Mod-d spawn dmenu_run
hc keybind $Mod+F1 spawn thunar
hc keybind $Mod+F2 spawn qalculate-gtk
hc keybind $Mod+F3 spawn firefox
hc keybind $Mod+F4 spawn thunderbird
hc keybind $Mod+F5 spawn telegram-desktop
hc keybind $Mod+F6 spawn bleachbit
hc keybind $Mod+F7 spawn libreoffice --writer
hc keybind $Mod+F12 spawn xfce4-screenshooter
#
#Close
hc keybind $Mod+F10 mode "$mode_system"
 
# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-j     focus left
hc keybind $Mod-k     focus down
hc keybind $Mod-i     focus up
hc keybind $Mod-l   focus right
 
# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-j     shift left
hc keybind $Mod-Shift-k     shift down
hc keybind $Mod-Shift-i     shift up
hc keybind $Mod-Shift-l     shift right
 
# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode
 
# resizing frames
resizestep=0.05
hc keybind $Mod-Control-j       resize left +$resizestep
hc keybind $Mod-Control-k       resize down +$resizestep
hc keybind $Mod-Control-i       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep
 
# tags
tag_names=("I" "II" "III" "IV" "V" "VI" "VII" "VIII" "IX" "X")
#tag_names=( {1..9} 0 )
tag_keys=( {1..9} 0 )
 
hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done
 
 
start all windows in floating mode
for attr in $(herbstclient complete 1 attr tags.by-name); do
        herbstclient attr "$attr.floating" true
    done
 
 
# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
 
 
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1
 
# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize
 
# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-Shift-u jumpto urgent
 
# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#151515'
# panel color 
hc set frame_border_normal_color '#151515'
hc set frame_bg_normal_color '#252525'
#hc set framme_bg_normal_color '#ffffff'
#blank window frame thing
#hc set frame_bg_active_color '#917154'
hc set frame_bg_active_color '#303030'
hc set frame_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 2
 
#set selected 'window'and selected workspace through its attr
#Color wm 
hc attr theme.active.color '#CC9900'
#hc attr theme.active.color '#cd749c'
#hc attr theme.active.color '#454545'
hc attr theme.normal.color  '#353535'
hc attr theme.urgent.color '#ffffff'
hc attr theme.inner_width 2
hc attr theme.outer_width 2
#hc attr theme.inner_color '#202020'
hc attr theme.inner_color '#252525'
hc attr theme.border_width 6
hc attr theme.floating.border_width 6
hc attr theme.floating.outer_width 2
hc attr theme.floating.inner_width  2
hc attr theme.floating.outer_color '#252525'
hc attr theme.floating.inner_color  '#252525'
hc attr theme.active.inner_color '#252525'
hc attr theme.active.outer_color '#252525'
hc attr theme.background_color '#202020'
 
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0  
hc set smart_frame_surroundings 1
hc set focus_follows_mouse 1
hc set mouse_recenter_gap 0
 
# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminalsy
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'
 

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors
 
# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done
herbstclient chain $cmds&
hc spawn stalonetray -bg "#333333" -i 17 --grow-gravity "E" --geometry 1x1-0+0


