#!/usr/bin/env bash
#
~/.Scrips/wal -i ~/Imágenes/Wallpapers/ -o wal-set -a 95
source "${HOME}/.cache/wal/colors.sh"

reload_dunst() {
    pkill dunst && \
        dunst \
            -lb "$color15" \
            -nb "$color15" \
            -cb "$color15" \
            -lf "$color0"  \
            -bf "$color0"  \
            -cf "$color9"  \
            -fn "${DUNST_FONT:-Artwiz Lemon 7}" \
            -geometry "${DUNST_SIZE:-300x30-40+40}" &
}

set_bar() {
    pkill bar
    bar "$color15" "$color0" 2>/dev/null &

main() {
    reload_dunst &
    set_bar &
    set_scss &
}

main >/dev/null 2>&1