#!/bin/bash

# Copyright (C) 2017 Moisés (d1nam0)                         

# This program is free software: you can redistribute it and/or modify             
# it under the terms of the GNU General Public License as published by             
# the Free Software Foundation, either version 3 of the License, or                
# (at your option) any later version.                                              

# This program is distributed in the hope that it will be useful,                  
# but WITHOUT ANY WARRANTY; without even the implied warranty of                   
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                    
# GNU General Public License for more details.                                     

# You should have received a copy of the GNU General Public License                
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# information d1nam0@openmailbox.org

clear
echo " *** SCRIPT CPU-FREQ SCALING  *** "
echo " SELECCIONA UNA OPCIÓN. "
echo " 1.-Powersave"
echo " 2.-Schedutil"
echo " 3.-Ondemand----(Recomendado para AMD)"
echo " 4.-Performance"
echo " 5.-Conservative"
echo " 6.-Userspace----(Asigna una frecuencia de forma manual)"
echo " 7.-¿Qué frecuencia tengo?"
echo " 8.-CPU frequency-info---(Ver frecuencias a las que se puede alcanzar"
echo "****************************************"
echo " 9.-Cambiar de forma permanente governor"
echo "*****************************************" 
echo " 10.-Salir"
echo ""
read -p "OPCIÓN: " OPCION
case $OPCION in
1) sudo cpupower frequency-set  -r -g powersave;;
2) sudo cpupower frequency-set  -r -g schedutil;;
3) sudo cpupower frequency-set  -r -g ondemand;;
4) sudo cpupower frequency-set  -r -g performance;;
5) sudo cpupower frequency-ser  -r -g conservative;;
6) echo -n " *** Ingresa de forma manual la frecuencia *** "
read freq
sudo cpupower frequency-set -f $freq;;
7) echo "**** Frecuencia actual ****: "
echo "****************************** "
cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor ;;
8) cpupower frequency-info ;;
9) sudo nano /etc/default/cpupower ;;
10) exit;;
*) echo " OPCIÓN NO VÁLIDA "
exit 1;;
esac