#!/bin/bash

if [ $USER != root ]; then
  echo ">> Error: debes ser root"
  echo ">> Terminando la ejecución del script ..."
  exit 0
fi

echo
echo ">> Borrando la cache de pacman ..."
echo
pacman -Scc
echo
echo ">> Borrando archivos de configuración obsoletos ..."
echo
sudo pacman -Ru $(pacman -Qdtq)
echo
echo ">> Vaciando todas las papeleras ..."
echo
rm -rf /home/*/.local/share/Trash/*/** &> /dev/null
rm -rf /root/.local/share/Trash/*/** &> /dev/null
echo
echo ">> Eliminando la caché de las imágenes [thumbnails] ..."
echo
rm -rf /home/*/.thumbnails/*/** &> /dev/null
rm -rf /root/.thumbnails/*/** &> /dev/null
echo
echo ">> Vaciando carpetas temporales [/tmp] ..."
echo
rm -rf /tmp/yaourt-tmp-[b]arcibel[/b]/*/** &> /dev/null
echo
sleep 2
echo ">> Se han realizado todas las tareas correctamente. Hasta pronto!"
echo