#!/bin/bash

active="$(pacmd list-sinks |awk '/* index:/{print $3}')"
vol="$(pacmd list-sinks |grep -A 15 'index: '$active'' |grep 'volume:' |egrep -v 'base volume:' |awk -F : '{print $3}' |grep -o -P '.{0,3}%'|sed s/.$// |tr -d ' ')%"

echo $vol
