#!/bin/bash 

dir=$(dirname $0)
source $dir/util.sh

full=""
short=""
status=0

URL='http://www.accuweather.com/es/mx/mexico-city/242560/weather-forecast/242560'
SITE="$(curl -s "$URL")"

weather="$(echo "$SITE" | awk -F\' '/acm_RecentLocationsCarousel\.push/{print $14 }'| head -1)"
temp="$(echo "$SITE" | awk -F\' '/acm_RecentLocationsCarousel\.push/{print $12 }'| head -1)"

if [[ $weather == *thunder* || $weather == *Thunder* ]]; then
    icon=""
else
    if [[ $weather == *rain* || $weather == *Rain* ]]; then
        icon=""
    else
        if [[ $weather == *cloud* || $weather == *Cloud* ]]; then
            icon=""
        else
            icon=""
        fi
    fi
fi

full="$icon $temp°"
short="$temp°"

echo $full
echo $short
exit $status

